scenario 3:

I have an issue with my ansible playbook. Im trying to copy a file from a remote host into ansible-controller(localhost) and its giving me this error:   


 [10.2.3.200] => {"changed": false, "checksum": "a2ff3c6cbca0d61d8fc0190aacc18029b7a547ea", "dest": "/home/sftproot/external/sbc-V10.01.03-R001.x86_64.md5", "gid": 0, "group": "root", "mode": "0644", "owner": "root", 
 "path": "/home/sftproot/external/sbc-V10.01.03-R001.x86_64.md5", "secontext": "unconfined_u:object_r:user_home_t:s0", "size": 66, "state": "file", "uid": 0}

Here is a snippet of the simple playbook executed:

```
playbook:
- hosts: sbcadmin
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python
    ansible_host: 10.2.3.200
    ansible_port: 2024
  tasks:
    - name: Copy packages to remote server using SCP
      ansible.builtin.copy:
        src: /opt/SBCImage/sbc-V10.01.03-R001.x86_64.md5
        dest: /home/sftproot/external/
      delegate_to: localhost
      vars:
        ansible_ssh_port: 2024
        ansible_ssh_user: linuxadmin
```

note: 
- assume `/home/sftproot/external/` exists in localhost

task:
- Identify the problem and provide a possible solution
- provide an explanation on your thought process










